version: '3.8'

services:
  wordpress:
    image: wordpress:${WORDPRESS_VERSION}
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.wordpress.entrypoints=web"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    volumes:
      - wordpress_data:/var/www/html
      - ./apache-config.conf:/etc/apache2/conf-available/custom.conf
    command: bash -c "ln -s /etc/apache2/conf-available/custom.conf /etc/apache2/conf-enabled/custom.conf && apache2-foreground"

  db:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
    name: ${TRAEFIK_NETWORK}

volumes:
  wordpress_data:
  db_data:

